"""State schemas and type definitions for the trading orchestrator."""

from typing import Annotated, Any, Literal, Sequence
from datetime import datetime
from enum import Enum
from pydantic import BaseModel, Field
import operator


class WorkflowStage(str, Enum):
    """Stages in the trading bot development workflow."""
    INITIALIZATION = "initialization"
    DATA_PREPARATION = "data_preparation"
    FEATURE_DISCOVERY = "feature_discovery"
    MODEL_TRAINING = "model_training"
    VALIDATION = "validation"
    SIGNAL_EVALUATION = "signal_evaluation"
    RISK_ASSESSMENT = "risk_assessment"
    HUMAN_REVIEW = "human_review"
    DEPLOYMENT = "deployment"
    COMPLETED = "completed"
    FAILED = "failed"


class AgentRole(str, Enum):
    """Specialized agent roles in the system."""
    SUPERVISOR = "supervisor"
    DATA_ENGINEER = "data_engineer"
    SMC_ANALYST = "smc_analyst"
    ML_ENGINEER = "ml_engineer"
    RISK_MANAGER = "risk_manager"
    VALIDATION_AGENT = "validation_agent"
    SIGNAL_EVALUATOR = "signal_evaluator"


class Message(BaseModel):
    """A message in the agent communication system."""
    role: AgentRole
    content: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    metadata: dict[str, Any] = Field(default_factory=dict)


class DatasetInfo(BaseModel):
    """Information about the trading dataset."""
    symbol: str
    timeframe: str
    start_date: datetime
    end_date: datetime
    total_bars: int = 0
    train_bars: int = 0
    validation_bars: int = 0
    test_bars: int = 0
    features: list[str] = Field(default_factory=list)
    quality_score: float = 0.0
    forexsb_integration: bool = False
    metadata: dict[str, Any] = Field(default_factory=dict)


class FeatureSet(BaseModel):
    """A set of features for model training."""
    feature_names: list[str]
    feature_importance: dict[str, float] = Field(default_factory=dict)
    smc_indicators: list[str] = Field(default_factory=list)
    wyckoff_phases: list[str] = Field(default_factory=list)
    ict_concepts: list[str] = Field(default_factory=list)
    technical_indicators: list[str] = Field(default_factory=list)
    correlation_matrix: dict[str, dict[str, float]] = Field(default_factory=dict)
    validation_score: float = 0.0


class ModelMetrics(BaseModel):
    """Metrics for a trained model."""
    accuracy: float = 0.0
    precision: float = 0.0
    recall: float = 0.0
    f1_score: float = 0.0
    sharpe_ratio: float = 0.0
    sortino_ratio: float = 0.0
    max_drawdown: float = 0.0
    win_rate: float = 0.0
    profit_factor: float = 0.0
    avg_trade_duration: float = 0.0
    total_trades: int = 0
    overfitting_score: float = 0.0
    walk_forward_results: dict[str, Any] = Field(default_factory=dict)


class ModelConfig(BaseModel):
    """Configuration for a trained model."""
    model_type: str = "lightgbm"
    hyperparameters: dict[str, Any] = Field(default_factory=dict)
    feature_set: FeatureSet | None = None
    training_date: datetime = Field(default_factory=datetime.utcnow)
    model_version: str = "1.0.0"
    metrics: ModelMetrics = Field(default_factory=ModelMetrics)
    checkpoint_path: str | None = None


class TradingSignal(BaseModel):
    """A trading signal generated by the model."""
    signal_id: str
    timestamp: datetime
    symbol: str
    direction: Literal["long", "short", "neutral"]
    confidence: float
    entry_price: float | None = None
    stop_loss: float | None = None
    take_profit: float | None = None
    position_size: float = 0.0
    risk_reward_ratio: float = 0.0
    smc_alignment: bool = False
    filters_passed: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)


class RiskAssessment(BaseModel):
    """Risk assessment for a trading signal or portfolio."""
    max_position_size: float
    kelly_fraction: float
    var_95: float = 0.0
    cvar_95: float = 0.0
    portfolio_correlation: float = 0.0
    margin_requirement: float = 0.0
    risk_score: float = 0.0
    approved: bool = False
    rejection_reason: str | None = None


class ValidationResult(BaseModel):
    """Results from model validation."""
    walk_forward_passed: bool = False
    overfitting_detected: bool = False
    statistical_significance: float = 0.0
    robustness_score: float = 0.0
    out_of_sample_metrics: ModelMetrics = Field(default_factory=ModelMetrics)
    validation_errors: list[str] = Field(default_factory=list)
    approved: bool = False


class AgentState(BaseModel):
    """State for the multi-agent orchestration system."""

    # Workflow control
    stage: WorkflowStage = WorkflowStage.INITIALIZATION
    current_agent: AgentRole | None = None
    next_agent: AgentRole | None = None
    iteration: int = 0
    max_iterations: int = 10

    # Communication
    messages: Annotated[Sequence[Message], operator.add] = Field(default_factory=list)

    # Task configuration
    task_description: str = ""
    task_parameters: dict[str, Any] = Field(default_factory=dict)

    # Data state
    dataset: DatasetInfo | None = None

    # Feature engineering state
    candidate_features: list[FeatureSet] = Field(default_factory=list)
    selected_features: FeatureSet | None = None

    # Model training state
    trained_models: list[ModelConfig] = Field(default_factory=list)
    best_model: ModelConfig | None = None
    training_progress: float = 0.0

    # Signal generation state
    generated_signals: list[TradingSignal] = Field(default_factory=list)
    filtered_signals: list[TradingSignal] = Field(default_factory=list)

    # Risk management state
    risk_assessments: dict[str, RiskAssessment] = Field(default_factory=dict)
    portfolio_allocation: dict[str, float] = Field(default_factory=dict)

    # Validation state
    validation_results: list[ValidationResult] = Field(default_factory=list)
    final_validation: ValidationResult | None = None

    # Human-in-the-loop
    requires_human_approval: bool = False
    human_feedback: str | None = None
    approval_stage: str | None = None

    # Error handling
    errors: Annotated[Sequence[str], operator.add] = Field(default_factory=list)
    warnings: Annotated[Sequence[str], operator.add] = Field(default_factory=list)

    # Metadata
    workflow_id: str = ""
    started_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: datetime | None = None
    checkpoints: dict[str, str] = Field(default_factory=dict)


class GraphConfig(BaseModel):
    """Configuration for the graph execution."""

    # Execution settings
    enable_checkpointing: bool = True
    checkpoint_dir: str = "./checkpoints"
    enable_streaming: bool = True
    enable_parallel_execution: bool = True

    # Agent timeouts
    agent_timeout_seconds: int = 300

    # Human-in-the-loop
    enable_human_approval: bool = True
    approval_stages: list[WorkflowStage] = Field(
        default_factory=lambda: [
            WorkflowStage.MODEL_TRAINING,
            WorkflowStage.SIGNAL_EVALUATION,
            WorkflowStage.DEPLOYMENT
        ]
    )

    # Retry configuration
    max_retries: int = 3
    retry_delay_seconds: float = 1.0

    # Resource limits
    max_concurrent_agents: int = 3
    memory_limit_mb: int = 4096
